### ISSUE TITLE
Adjusting the volume is missing on Apple Home

### ISSUE THREAD

**Issue by fwiehl** [DoctorNSA/homebridge-musiccast-tv#1]
Is it possible to change the volume in Apple Home. I have installed it but it is only possible to select the input and turn the speaker on/off. But it is not possible to adjust the volume

**Comment by aangert** [comment]
It is currently not possible to change the volume in Home, however you can change the volume by adding the Apple TV Remote Widget to your Control Center.
![97891B59-3029-4684-9EB3-A6C157C80E2A](https://user-images.githubusercontent.com/40806022/74862488-8871ca00-534c-11ea-8c8f-5f2add6acc04.jpeg)

**Comment by fwiehl** [comment]
I have this widget an my musiccast is listed there, but there is no function on it. ( I have not an apple tv, but an ipad as control center installed

**Comment by aangert** [comment]
After opening the widget you can change volume by using your devices physical volume buttons. (You should update to version 1.2.3 or newer, otherwise this will crash Homebridge)
