### ISSUE TITLE
Make Serial Number editable in config.json

### ISSUE THREAD

**Issue by thomaskoch81** [DoctorNSA/homebridge-musiccast-tv#10]
**Is your feature request related to a problem? Please describe.**
My Yamaha musiccast accessory is detedcted in the Apple Home app, but not in 3rd party apps like Elegato Eve. I fear it might have to do with the fix serial number of "123-456-789".

**Describe the solution you'd like**
Could you provide the possibility to set the serial number through the config file? It could be optional, default value can still be "123-456-7892

Thanks!

**Comment by aangert** [comment]
this will be added in V1.6.2
