### ISSUE TITLE
Volume Control would be awesome

### ISSUE THREAD

**Issue by albi** [DoctorNSA/homebridge-musiccast-tv#11]
This is a neat plugin. Best implementation I've seen so far for MusicCast devices. Is there any Volume Control planned?

**Comment by aangert** [comment]
There is currently volume control via the Apple TV Remote widget. After adding the TV widget to the control centre you can use your phone's volume buttons to change the volume

**Comment by albi** [comment]
Unfortunately that's not working with my TV :(

**Comment by aangert** [comment]
It doesn't have to work with your tv, your MusicCast device appears in the TV widget like [every HomeKit enabled TV](https://www.reddit.com/r/appletv/comments/b8sqe9/a_look_at_the_remote_widget_controlling_an/)

**Comment by albi** [comment]
Unfortunately not really on my side. The screenshot I’ve taken is my HomeKit TV widget. It is only the tv that is available and when I press one of these buttons the TV is shutting down. But it definitely does not control the MusicCast device. 
![D861B687-CA2D-4AE3-9FDF-80EDA3897102](https://user-images.githubusercontent.com/89451/101518824-b5967400-3982-11eb-898a-ed396cfbd707.png)

**Comment by aangert** [comment]
Do you publish more than one HomeKit TV per homebridge instance? If there's more than one television per homebridge instance, just one will be visible in the TV widget.

**Comment by albi** [comment]
There is one Panasonic TV on/off switch added. Tomorrow I‘ll remove that one and try again.

**Comment by aangert** [comment]
Did it work?

**Comment by albi** [comment]
Ups, forgot about it. I'll have a try on the weekend

**Comment by albi** [comment]
I've removed the Panasonic TV from HomeKit, but the TV widget still won't work with my Yamaha WXC-50.

**Comment by albi** [comment]
Just made a firmware update of the Yamaha WXC-50 and now I got it working! 👍
