### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by quartist** [DoctorNSA/homebridge-musiccast-tv#13]
Hi,

It is possible to add an slidebar for volume control?
In plugin: https://www.npmjs.com/package/homebridge-yamaha_mc3
this working in implementation like a"fan".
All of my functions in soundbar are controlled from Home app - turn on/of, change input but when i need change volume level I must to looking for IR remote :/

**Comment by aangert** [comment]
See #1, #11

**Comment by aangert** [comment]
I'm now planning on adding an optional fan service in v1.7
