### ISSUE TITLE
New button play favorites radio list or favorite playlist ?

### ISSUE THREAD

**Issue by jakubbrach** [DoctorNSA/homebridge-musiccast-tv#14]
Hi
 Is it possible to add support for starting the radio from the list of favorites or a favorite playlist? Maybe as an extra button. 

Thanks

**Comment by aangert** [comment]
There should be a way to do this, I'll try to look into the API Documentation next week

**Comment by marvelousmo** [comment]
any news on that?

**Comment by aangert** [comment]
Recalling a tuner preset should be possible using http://{host}/YamahaExtendedControl/v1/tuner/recallPreset?zone=main&band=fm&num=13

Implementing and testing these changes might take a few more weeks

**Comment by aangert** [comment]
You can test this Feature by installing v1.8 and adding `buttonBand`, `buttonName` and `buttonNumber` to your config.json. Please report back if it doesn't work as intended

**Comment by jakubbrach** [comment]
Hello

Thanks for adding this feature.
Button: buttonBand works ok
I don't know how to set:
ButtonName and buttonNumber. I have it set like this:
{
             "powerOnInput": "net_radio",
             "inputs": {
                 "net_radio": "Online radio",
                 "tv": "tv"
             },
             "accessory": "MusicCastTV",
             "volumeName": "TV",
             "model": "Yamaha BAR 400",
             "volume": "100",
             "ip": "192.168.1.107",
             "maxvol": "161",
             "name": "Soundbar",
             "volumeFan": "1",
             "buttonNumber": "1",
             "buttonName": "test",
             "buttonBand": "fm"
         },

And nothing happens. I thought the button would change the radio station saved in favorites to number one

**Comment by aangert** [comment]
`buttonNumber` should be the number in your list of favourites and `buttonName` should be the name to display on the button in homebridge.
I will read the API documentation again in the next few weeks to find the bug

**Comment by jakubbrach** [comment]
> `buttonNumber` should be the number in your list of favourites and `buttonName` should be the name to display on the button in homebridge.
> I will read the API documentation again in the next few weeks to find the bug

hi

`url: 'http://' + this.ip + '/YamahaExtendedControl/v1/**tuner**/recallPreset?zone=' + this.zone + '&band=' + this.buttonBand + '&num=' + this.buttonNumber,
			method: 'GET',`


Replacement : tuner on netusb - it helped. Now everything works

**Comment by aangert** [comment]
I will test and release this bugfix next weekend

**Comment by aangert** [comment]
Could you please test v1.8.1 and report back
