### ISSUE TITLE
This plugin slows down Homebridge

### ISSUE THREAD

**Issue by ShadowFM** [DoctorNSA/homebridge-musiccast-tv#17]
**Describe the bug**
A few HomBridge restarts ago I got the message "This plugin slows down Homebridge" for the musiccast-tv app

**Expected behavior**
Sometimes this and other device become unbehavior into the HomBridge till the next reboot

**Log files**
- [homebridge-musiccast-tv] This plugin slows down Homebridge. The read handler for the characteristic 'Active' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

**Additional context**
Ubuntu 20.04
Node.js Version | v14.17.0
Npm Version | v6.13.4

**Comment by aangert** [comment]
Unfortunately this plugin relies on a network connection to the MusicCast Device. I found one issue with the getActive handler, but you might be able to fix the unresponsive bridge issue using a[child bridge](https://github.com/homebridge/homebridge/wiki/Child-Bridges#how)

**Comment by aangert** [comment]
The next update should include some speed improvements and fix this error, however using a child bridge is still the best way forward
