### ISSUE TITLE
Alexa Input not found

### ISSUE THREAD

**Issue by LiSchill** [DoctorNSA/homebridge-musiccast-tv#18]
I just want to inform you, that I have an additional input which isn't listed yet. It would be great if could implement the input.
<img width="561" alt="Bildschirmfoto 2021-08-24 um 18 51 51" src="https://user-images.githubusercontent.com/89475909/130657821-cb2130d2-0662-4fec-8c7b-be64d6e22989.png">

**Comment by aangert** [comment]
Could you please post the JSON from `http://<ip>/YamahaExtendedControl/v1/system/getFeatures`

**Comment by LiSchill** [comment]
Yes, of course :)

{"response_code":0,"system":{"func_list":["wired_lan","wireless_lan","network_standby","network_standby_auto","bluetooth_standby","bluetooth_tx_setting","bluetooth_tx_connectivity_type","dfs_option","headphone","zone_b_volume_sync","hdmi_out_1","airplay","disklavier_settings","background_download","remote_info","network_reboot","system_reboot","name_text_avr","hdmi_standby_through","analytics"],"zone_num":2,"input_list":[{"id":"napster","distribution_enable":true,"rename_enable":false,"account_enable":true,"play_info_type":"netusb"},{"id":"spotify","distribution_enable":true,"rename_enable":false,"account_enable":false,"play_info_type":"netusb"},{"id":"qobuz","distribution_enable":true,"rename_enable":false,"account_enable":true,"play_info_type":"netusb"},{"id":"tidal","distribution_enable":true,"rename_enable":false,"account_enable":true,"play_info_type":"netusb"},{"id":"deezer","distribution_enable":true,"rename_enable":false,"account_enable":true,"play_info_type":"netusb"},{"id":"amazon_music","distribution_enable":true,"rename_enable":false,"account_enable":true,"play_info_type":"netusb"},{"id":"alexa","distribution_enable":true,"rename_enable":false,"account_enable":false,"play_info_type":"netusb"},{"id":"airplay","distribution_enable":false,"rename_enable":false,"account_enable":false,"play_info_type":"netusb"},{"id":"mc_link","distribution_enable":false,"rename_enable":true,"account_enable":false,"play_info_type":"netusb"},{"id":"server","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"netusb"},{"id":"net_radio","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"netusb"},{"id":"bluetooth","distribution_enable":true,"rename_enable":false,"account_enable":false,"play_info_type":"netusb"},{"id":"usb","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"netusb"},{"id":"tuner","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"tuner"},{"id":"hdmi1","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"hdmi2","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"hdmi3","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"hdmi4","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"av1","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"av2","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"av3","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"audio1","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"audio2","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"audio3","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"},{"id":"aux","distribution_enable":true,"rename_enable":true,"account_enable":false,"play_info_type":"none"}],"bluetooth":{"update_cancelable":true,"tx_connectivity_type_max":2},"web_control_url":"\/AdvancedSettings.html?mc=true"},"zone":[{"id":"main","func_list":["power","sleep","volume","mute","sound_program","direct","enhancer","tone_control","dialogue_level","subwoofer_volume","signal_info","prepare_input_change","link_control","link_audio_delay","scene","contents_display","cursor","menu","actual_volume","surr_decoder_type","extra_bass","adaptive_drc"],"input_list":["napster","spotify","qobuz","tidal","deezer","amazon_music","alexa","airplay","mc_link","server","net_radio","bluetooth","usb","tuner","hdmi1","hdmi2","hdmi3","hdmi4","av1","av2","av3","audio1","audio2","audio3","aux"],"sound_program_list":["munich","vienna","chamber","cellar_club","roxy_theatre","bottom_line","sports","action_game","roleplaying_game","music_video","standard","spectacle","sci-fi","adventure","drama","mono_movie","2ch_stereo","5ch_stereo","surr_decoder","straight"],"surr_decoder_type_list":["toggle","dolby_pl2x_movie","dolby_pl2x_music","dolby_pl2x_game","dts_neo6_cinema","dts_neo6_music"],"tone_control_mode_list":["manual"],"link_control_list":["speed","standard","stability"],"link_audio_delay_list":["audio_sync","balanced","lip_sync"],"range_step":[{"id":"volume","min":0,"max":161,"step":1},{"id":"tone_control","min":-12,"max":12,"step":1},{"id":"dialogue_level","min":0,"max":3,"step":1},{"id":"subwoofer_volume","min":-12,"max":12,"step":1},{"id":"actual_volume_db","min":-80.5,"max":16.5,"step":0.5},{"id":"actual_volume_numeric","min":0.0,"max":97.0,"step":0.5}],"scene_num":4,"cursor_list":["up","down","left","right","select","return"],"menu_list":["on_screen","top_menu","menu","option","display","help","home","mode","red","green","yellow","blue"],"actual_volume_mode_list":["db","numeric"],"ccs_supported":["connected_speaker"]},{"id":"zone2","zone_b":true,"func_list":["power","volume","mute","prepare_input_change","actual_volume"],"input_list":["napster","spotify","qobuz","tidal","deezer","amazon_music","alexa","airplay","mc_link","server","net_radio","bluetooth","usb","tuner","hdmi1","hdmi2","hdmi3","hdmi4","av1","av2","av3","audio1","audio2","audio3","aux"],"range_step":[{"id":"volume","min":0,"max":161,"step":1},{"id":"actual_volume_db","min":-80.5,"max":16.5,"step":0.5},{"id":"actual_volume_numeric","min":0.0,"max":97.0,"step":0.5}],"actual_volume_mode_list":["db","numeric"]}],"tuner":{"func_list":["am","fm","rds"],"range_step":[{"id":"am","min":531,"max":1611,"step":9},{"id":"fm","min":87500,"max":108000,"step":50}],"preset":{"type":"common","num":40}},"netusb":{"func_list":["recent_info","play_queue","mc_playlist","streaming_service_use"],"preset":{"num":40},"recent_info":{"num":40},"play_queue":{"size":200},"mc_playlist":{"size":200,"num":5},"net_radio_type":"airable"},"distribution":{"version":2.00,"compatible_client":[2],"client_max":19,"server_zone_list":["main"],"mc_surround":{"version":1.00,"func_list":["mcss_error_info"],"master_role":{"surround_pair":true,"stereo_pair":false,"subwoofer_pair":true},"slave_role":{"surround_pair_l_or_r":false,"surround_pair_lr":false,"subwoofer_pair":false}}},"ccs":{"supported":true}}

**Comment by aangert** [comment]
this should be fixed in v1.8.1

**Comment by LiSchill** [comment]
Perfect. It's working :) 👍👍 Thanks a lot!
