### ISSUE TITLE
Support Zones?

### ISSUE THREAD

**Issue by neodominous** [DoctorNSA/homebridge-musiccast-tv#22]
I would love to be able to allow for zoning with my receivers so I can control input and volume for my seperate Zones via Homekit

**Comment by benchristian88** [comment]
doesn't it already do that by adding "zone": "zone2", to the config.  ie add another accessory and add this line and you have two HomeKit remotes. works on mine

**Comment by neodominous** [comment]
Yup you are correct, figured it out on my own later.

**Comment by aangert** [comment]
Glad this could be resolved
