### ISSUE TITLE
Input shown as additional Tile

### ISSUE THREAD

**Issue by fwiehl** [DoctorNSA/homebridge-musiccast-tv#3]
Auf dem iPad werden Spotify/Airplay und Webradio als getrenntes Feld angezeigt. Dabei ist das Feld Webradio ohne Funktion. Das Webradio kann nicht eingeschaltet werden:

![2020-02-24 08_25_53-Window](https://user-images.githubusercontent.com/49639260/75135855-2108a100-56e3-11ea-93a9-cf33421fe979.jpg)

**Comment by aangert** [comment]
Das Problem kann man lösen, indem man Homebridge entfernt und neu koppelt

**Comment by fwiehl** [comment]
Homebridge entfernt und neu eingebunden. Jetzt geht es!
