### ISSUE TITLE
Feature Request: Option to set the Volume to a specific level after powering on

### ISSUE THREAD

**Issue by fwiehl** [DoctorNSA/homebridge-musiccast-tv#4]
Es wäre schön, wenn die Lautstärke beim Einschalten über HomeKit auf einen bestimmten Wert gesetzt wird. Auch wäre es schön, wenn man die Lautstärke über HomeKit steuern könnte.
Danke
fwiehl

**Comment by aangert** [comment]
Wird demnächst über ```powerOnVolume``` bereitgestellt

**Comment by aangert** [comment]
Wurde mit [v1.4.3](https://github.com/DoctorNSA/homebridge-musiccast-tv/releases/tag/v1.4.3) ergänzt

**Comment by aangert** [comment]
Die Lautstärke kann man über das Remote Widget im Kontrollzentrum steuern, indem man die hoch/ runter Tasten oder die Lautstärketasten am Gerät verwendet.

**Comment by aangert** [comment]
@fwiehl läuft die Funktion richtig?
