### ISSUE TITLE
Additional inputs for MusicCast Bar 400

### ISSUE THREAD

**Issue by Morinisti** [DoctorNSA/homebridge-musiccast-tv#5]
First: great plugin, thanks a lot!

Additional inputs for MusicCast Bar 400 would be nice:

"tv", "hdmi" and "analog"

Response json from getFeatures request attached. 

[getFeatures_MusicCast_Bar400.txt](https://github.com/DoctorNSA/homebridge-musiccast-tv/files/4302526/getFeatures_MusicCast_Bar400.txt)

**Comment by aangert** [comment]
These Inputs are added with 3ccd4b4c6a90b6d16158efb652bef72f262a823d and will be added in the next release, hopefully around Wednesday/Thursday this week

**Comment by aangert** [comment]
Should be fixed by [v1.4.3](https://github.com/DoctorNSA/homebridge-musiccast-tv/releases/tag/v1.4.3)

**Comment by Morinisti** [comment]
Perfect! Thanks a lot!
