### ISSUE TITLE
default input spotify

### ISSUE THREAD

**Issue by morningla** [DoctorNSA/homebridge-musiccast-tv#6]
i am able to successfully use Homekit to trigger the receiver to start playing music on FM Radio.  but inputs like Spotify requires additional action for any songs to start.  any solution to this?   thank you.

**Comment by aangert** [comment]
Can you check whether the input is actually switched to Spotify? Depending on the result the issue might be
- Input is not switched to Spotify correctly
- Input is switched to Spotify but no Music is being played

**Comment by morningla** [comment]
yes, it does switch to AirPlay.
I think I need to figure out a way to trigger spotify then also make it select AirPlay on the Yamaha receiver somehow.
looks pretty touch, any suggestions?

thank you

________________________________

**Comment by aangert** [comment]
Are you using Spotify directly(MusicCast input is Spotify) or Spotify via AirPlay (MusicCast input is AirPlay)?

**Comment by morningla** [comment]
I’m using Spotify in Airplay, is there an option to do this in musiccast?  It just opens Spotify app if i use the musiccast app

Sent from my iPhone

On May 17, 2020, at 2:03 PM, DoctorNSA <notifications@github.com> wrote:

﻿

Are you using Spotify directly(MusicCast input is Spotify) or Spotify via AirPlay (MusicCast input is AirPlay)?

**Comment by aangert** [comment]
If your device supports Spotify you can add it in your config.json via `“spotify”: “Spotify”`. 
You can get a list of supported inputs by accessing `http://<ip>/YamahaExtendedControl/v1/system/getFeatures`

**Comment by aangert** [comment]
If you are using AirPlay there is no way to automatically start Spotify via Airplay

**Comment by aangert** [comment]
@morningla Do you need additional help?

**Comment by morningla** [comment]
No i am ok, thank you

Sent from my iPhone

On Jun 8, 2020, at 11:39 AM, DoctorNSA <notifications@github.com> wrote:

﻿

@morningla<https://github.com/morningla> Do you need additional help?
