### ISSUE TITLE
The speaker tile (change volume) doesn't appear 

### ISSUE THREAD

**Issue by jmredfern** [DoctorNSA/homebridge-musiccast-tv#9]
Thanks for your musiccast plugin :)

I'm using it for a yamaha WXC-50, pre-amplifier. Hoping to use it to change input and volume.

**Describe the bug**
In the home app on ios:
The TV tile appears (switch input)
The speaker tile (change volume) doesn't appear 

Both appear in the homebridge accessories page.

**Expected behavior**
Both tiles appear in the home app in ios

**Additional context**
Ios 13.5.1

**Comment by aangert** [comment]
Could you post a picture of the homebridge accessories page?

**Comment by jmredfern** [comment]
![image](https://user-images.githubusercontent.com/3799803/87899446-0e7e6380-ca06-11ea-943c-73b6e7847d70.png)

The functionality works in the Homebridge UI

**Comment by aangert** [comment]
This service is not fully supported by the home app, but you can still change the TV volume via the control centre
